### ISSUE TITLE
Creating wallet with seed phrase

### ISSUE THREAD

**Issue by jdhoch** [marscoin/marscoin-archive#18]
Hello, is there anyway to create a wallet with a seed phrase (windows)? In other words, how do I recover the funds in a lost wallet?

**Comment by novalis78** [comment]
Yes, that will be possible with the new Marscoin Electrum Edition. https://github.com/marscoin/electrum-mars. If you have an existing regular Marscoin wallet, you can use the command "dumpprivkey" to export  your private keys. (https://chainquery.com/bitcoin-cli/dumpprivkey - syntax is the same for Marscoin)
