### ISSUE TITLE
0 active connection for the update of blockchain MARScoin wallet ?

### ISSUE THREAD

**Issue by Arakiss007** [marscoin/marscoin-archive#3]
Hello, i have installed the MARScoin wallet for windows.
But i think there is a problem with the blockchain connection.

Because i have : 0 active connection since one hour.

Is it normal?

Thanks you very much.

Best regards, 

Chris

**Comment by Palacius** [comment]
I have the same problem I tried to send some coins but they haven't arrived yet 😕

**Comment by novalis78** [comment]
Sometimes the windows wallet gets blocked. Try running it as administrator. It should start syncing automatically.
