### ISSUE TITLE
how to add new host addresses

### ISSUE THREAD

**Issue by ex-ex** [marscoin/marscoin-archive#9]
Hello how to add new host addresses. I've tried through Marscoin.conf file like so addnode = adsl-89-217-2-100.adslplus.ch: 8338. And through the program console. It seems that the program has added an address, when you enter it again, it says "Node already added". But it always connects to the same address. 107.170.70.121:8338 Not connected to other addresses.

![77786](https://user-images.githubusercontent.com/28987671/111289374-e8799380-8666-11eb-8fd5-833f68fb5abf.jpg)

**Comment by novalis78** [comment]
In your marscoin.conf file, try adding known Marscoin nodes like this:


addnode=107.170.27.222
addnode=107.170.70.121
addnode=91.206.16.214

You can find more nodes on our community discord server.
